---
# tasks file for java
- name: Download Java installer
  include_tasks: download.yml

- name: 'refreshing {{ java_latest_folder }} link to {{ java_folder }}'
  file:
    src: '{{ java_folder }}'
    dest: '{{ java_latest_folder }}'
    owner: root
    group: root
    state: link

- name: 'install Java environment variables'
  template:
    src: 'java.sh.j2'
    dest: '/etc/profile.d/java.sh'
    owner: root
    group: root
    mode: 0644

- name: 'link JDK binaries'
  become: true
  alternatives: link="/usr/bin/{{ item }}" name="{{ item }}" path="{{ java_folder }}/bin/{{ item }}" priority={{ java_bins_priority }}
  with_items: "{{ java_bins_jdk }}"
  when:
    - java_bins_update
    - java_type == 'jdk'

- name: 'link JRE binaries'
  become: true
  alternatives: link="/usr/bin/{{ item }}" name="{{ item }}" path="{{ java_folder }}/bin/{{ item }}" priority={{ java_bins_priority }}
  with_items: "{{ java_bins_server_jre }}"
  when:
    - java_bins_update
    - java_type == 'server_jre'